routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PrincipalController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']);

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicoes extends Model
{
    use HasFactory;

    public function getResistenciaInternaAttribute()
    {
        return $this->resistencia_carga * ($this->tensao_sem_carga / $this->tensao_com_carga - 1);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Medicoes;

class PrincipalController extends Controller {

    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = Medicoes::all();
        return view('medicoes',compact('medicoes'));
    }

    public function conclusoes(){
        return view('conclusoes');
    }

    public function principal(){
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }

    public function pagina2() {
        return view('pagina2');
    }

}

resources/views/conclusoes.blade.php
@extends('templates.base')

@section('conteudo')

<main>
    <br>
        <h1>Conclusões</h1>
   <br>



   
</br>
        <h2>Conclusão a resistência interna:</h2>
        <p>Após a realização do trabalho, podemos concluir que quanto maior a resistência interna da bateria, quer dizer que mais gasta ela está.</p>
        <h2>Conclusão sobre as pilhas/baterias:</h2>
        <p>Como a resistência interna da bateria representa o quão gasta ela está, podemos concluir que as baterias golite, elgin e duracell plus AA são as mais gastas.</p>
        <br>
        <h2>Conclusão geral sobre o trabalho:</h2>
</br>
        <h3>Programação em Automação:</h3>
        <p>Com a realização do trabalho, podemos ter um maior aprofundamento no estudo do CSS, Javascript e HTML e podemos realizar ligações entre todas estas linguagens de programação. O CSS é a folha de estilos, responsável por estilizar a página, o HTML é responsável pelas configurações gerais da página e o Javascript se encarrega de calcular as expressões. No caso, os cálculos foram da resistência de carga e resistência interna. </p>
        <h3>Eletroeletrônica:</h3>
        <p>Para a disciplina de eletroeletrônica, podemos calcular e medir na prática a tensão sem carga e a tensão com carga de pilhas ou baterias. Quanto à medida da tensão nominal, ela aparece escrita na carcaça da pilha ou bateria. A capacidade de corrente foi obtida através de pesquisas na internet. A reistẽncia de carga e a resistência interna foram calculadas por meio do javascript.</p>
    </main>

    @endsection

    @section('rodape')
        <h4>Rodapé da página principal</h4>
    @endsection

resources/views/medicoes.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Medições</h1>
        <hr>
        <h2>Resultados:</h2>
        <table class="table table-dark table-striped table-bordered" id="tbDados">
            <thead>
                <tr>
                    <th>Pilha/Bateria</th>
                    < th>Tensão Nominal (V)</>
                    <th>Capacidade de Corrente</th>
                    <th>Tensão sem carga (V)</th>
                    <th>Tensão com carga (V)</th>
                    <th>Resistência de carga(ohm)</th>
                    <th>Resistência interna (ohm)</th>
                </tr> 
            </thead>
            <tbody>
                @foreach($medicoes as $medicao)
                <tr>
                    <td>{{$medicao->pilha_bateria}}</td>
                    <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                    <td>{{$medicao->capacidade_corrente}}</td>
                    <td>{{$medicao->tensao_sem_carga}}</td>
                    <td>{{$medicao->tensao_com_carga}}</td>
                    <td>{{$medicao->resistencia_carga}}</td>
                    <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>
                </tr>
                @endforeach
           </tbody>
          
            
    </main>
    @endsection

    @section('rodape')
        <h4>Rodapé da página principal</h4>
    @endsection

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
    <h2>Pagina 1</h2>
    <hr>
@endsection

@section('rodape')
     <h4>Rodape da pagina 1</h4>
@endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
    <h2>Pagina 2</h2>
    <hr>
@endsection

@section('rodape')
     <h4>Rodape da pagina 2</h4>
@endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
    <h2>Pagina Principal</h2>
    <hr>
@endsection

@section('rodape')
     <h4>Rodape da pagina principal</h4>
@endsection

resources/views/principalBaterias.blade.php
@extends('templates.base')

@section('conteudo')
    <main>
        <h1>Turma 2D3 - Grupo 5</h1>
        <h2>Participantes</h2>
        <hr>
        <table class="table table-striped table-bordered" id="tabela1">
            <tr>
                <th>Matrícula</th>
                <th>Nome</th>
                <th>Função</th>
            </tr>
            <tr>
                <td>0072547</td>
                <td>Ana Clara Alves da Silva</td>.
                <td>Anotação e medição da tensão das pilhas e baterias</td>
            </tr>
            <tr>
                <td>0072557</td>
                <td>Leonardo Passos Sampaio</td>
                <td>Anotação e medição da tensão das pilhas e baterias</td>
            </tr>
            <tr>
                <td>0072530</td>
                <td>Mateus Rocha Oliveira</td>
                <td>Gerente e desenvolvedor css e javascript</td>
            </tr>
            <tr>
                <td>0066066</td>
                <td>Victor Henrique Duarte Maia</td>
                <td>Desenvolvedor html</td>
            </tr>
        </table>
        <img class="grupo" src="imgs/fotogrupo.jpg" alt="Componentes do grupo">
    </main>
   
@endsection

@section('rodape')
    <h4>Rodapé da página principal</h4>
@endsection

resources/views/procedimento.blade.php
@extends('templates.base')

@section('conteudo')

    <main>
        <h1>Procedimentos</h1>
        <h2>Materiais:</h2>
        <p>Multímetro</p>
        <p>Resistência de 23.8 ohms</p>
        <h2>O que foi feito?</h2>
        <p>Primeiramente, medimos o valor da resistência. Após isto, medimos o valor da tensão sem carga, medindo utilizando o multímetro diretamente nas pilhas e baterias.</p>
        <p>Após isto, medimos o valor da tensão com carga, pegando o multímetro encostando com a ponta da resistência e do outro lado, ligando diretamente na pilha.</p>
        <p>Os valores da resitência de carga(ohm) e da 	Resistência interna(ohm) foram calculados por meio do javascript</p>
        <h2>Imagens das baterias e pilhas medidas:</h2>
        <img class="bateria1" src="../imgs/bateriagolite.jpg" alt="Bateria Golite" height="400" width="400">
        <img class="bateria2" src="../imgs/pilhaluatek.jpg" alt="Bateria Luatek" height="400" width="400">
        <img class="pilha1" src="../imgs/duracellAA.jpg" alt="Pilha Duracell AA" height="400" width="400">
        <img class="pilha2" src="../imgs/duracellAAA.jpg" alt="Pilha Duracell AAA" height="400" width="400">
        <img class="pilha3" src="../imgs/panassonicAA.jpg" alt="Pilha Panassonic AA" height="400" width="400">
        <img class="pilha4" src="../imgs/JVX.jpg" alt="Pilha JVX" height="400" width="400">
        <img class="bateria3" src="../imgs/bateriaelgin.jpg" alt="Bateria Elgin" height="400" width="400">
        <img class="bateria4" src="../imgs/philipsAAA.jpg" alt="Pilha Philips AAA" height="400" width="400">
        <img class="bateria5" src="../imgs/bateriafreedom.jpg" alt="Bateria Freedom" height="400" width="400">
        <img class="bateria6" src="../imgs/bateriaunipower.jpg" alt="Bateria unipower" height="400" width="400">
    </main>

    @endsection

    @section('rodape')
        <h4>Rodapé da página principal</h4>
    @endsection

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bateriasaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css') }}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
                <li><a href="{{ route('conclusoes') }}">Conclusões</a></li>
            </ul>
        </nav>

        @yield("conteudo")
        <div class="rodape container-md">
            @yield("rodape")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
@extends('templates.base')

@section('conteudo')

    <main>
        <h1>Teoria</h1>
        <hr> Determinar a resistência interna de uma fonte de tensão real</hr>
        <p>Uma fonte de tensão real é constituída de uma fonte de tensão ideal (E) em série com a sua resistência interna (r) como mostra o circuito abaixo:</p>
        <img src="../imgs/fonte-real (1).png" alt="fonte de tensão com resistência interna">
        <p>Para conhecermos o valor da tensão interna da fonte (E) basta medirmos diretamente essa fonte com um multímetro desde que não haja nenhuma carga ligada a essa fonte:</p>
        <img src="../imgs/fonte-real 2.png" alt="queda de tensão">
        <p>Quando conectamos uma carga (R) a essa fonte, circulará uma corrente (I) que produzirá queda de tensão interna (Vr) e a queda de tensão externa (VR):</p>
        <img src="../imgs/f2.png" alt="queda de tensão interna e queda de tensão externa">
        <p></p>Através da equação do divisor de tensão temos que:</p>
        <img src="../imgs/fonte-real 2.png" alt="equação do divisor de tensão">
        <p>Passando o termo "r+R" multiplicando à esquerda e o termo "VR" dividindo à direita fica:</p>
        <img src="../imgs/CodeCogsEqn.png" alt="equação do divisor após resolução parcial">
        
        <p>Isolando "r" temos que:</p>
        <img src="../imgs/CodeCogsEqn (2).png" alt="equação após isolar o 'R'">
        <p>Colocando "R" em evidência fica:</p>
        <img src="../imgs/CodeCogsEqn (3).png" alt="equação com o 'R' em evidência">
        <p>Dessa forma podemos medir, indiretamente, a resistência interna de uma pilha ou de uma bateria, através da medição de sua tensão interna (sem carga) "E", da tensão externa (com carga) "VR" e da própria resistência externa "R" e  aplicando a equação da resistência interna "r"!</p>
        </p>
    
    </main>
    
    @endsection

    @section('rodape')
        <h4>Rodapé da página principal</h4>
    @endsection